### ISSUE TITLE
not working - serious errors

### ISSUE THREAD

**Issue by ghost** [gziolo/es6-browser-boilerplate#2]
First off there is a bunch of errors NPM when you try to intall it.
Then when you try to run `gulp` this shows up:

Running "karma:continuous" (karma) task
WARN [watcher]: Pattern "C:/xampp/htdocs/babel/bower_components/*_/_.js" does not match any file.
INFO [karma]: Karma v0.12.36 server started at http://localhost:9877/
INFO [launcher]: Starting browser Firefox
WARN [web-server]: 404: /favicon.ico
WARN [web-server]: 404: /favicon.ico
INFO [Firefox 38.0.0 (Windows 10 0.0.0)]: Connected on socket LseHAB8chkmozkZ9WGhS with id 35092052
Firefox 38.0.0 (Windows 10 0.0.0) ERROR: 'There is no timestamp for /base/bower_components/jquery/dist/jquery.js!'
WARN [web-server]: 404: /base/bower_components/jquery/dist/jquery.js
Firefox 38.0.0 (Windows 10 0.0.0) ERROR
  Error: Script error for: jquery
  http://requirejs.org/docs/errors.html#scripterror
  at C:/xampp/htdocs/babel/node_modules/requirejs/require.js:166

Finished in 0.072 secs / 0 secs

SUMMARY:
√ 0 tests completed
Warning: Task "karma:continuous" failed. Use --force to continue.

**Comment by gziolo** [comment]
What version of Node are you using?
Do you have jQuery folder downloaded by Bower to `bower_component` folder? If not please make sure you run this:
`bower install`
or simply to run everything that is executed on Travis CI:
`npm test`
I tested it locally on Node v0.12.0 and it works fine.

**Comment by ghost** [comment]
Hi. Are you testing on windows or Mac?  Errors happened on windows. Jquery was installed. 

I also `$ npm install jquery` as an attempt so I got it in the folder. And adjusted the files thereafter.

At that time I was using nodejs 12. It also had issues with npm dependencies.

Anyway. After research I figure nodejs 12 has a lot of bug so I downgraded to 12.3. And discovered that windows 10 latest preview  build and nodejs are enemies sometimes.

So I'm running iojs now.

**Comment by gziolo** [comment]
Hi, I'm on Windows 8.1. jQuery needs to be installed by bower, not npm, it has most likely different folder structure. Does it work with iojs? Travis build triggered 28 days ago on iojs worked fine.

**Comment by ghost** [comment]
Iojs works fine. But why rely on jquery? Is this only client side? Or server side too? Should be easier to set up some fixtures

**Comment by gziolo** [comment]
You can remove that completely, this was added just to show how to import dependency downloaded from bower :)
This boilerplate will work only on client side, because it transpiles ES6 modules to AMD using RequireJS. For server side there are other boilerplates that use browserify or webpack. Both will work also on client side.

**Comment by ghost** [comment]
Some clients of mine needed a simple solution therefor I'm here. And they
only use it client side.

I'm using myself my own setup with mocha and sinon - chain.  For server
side I'm using sourcemaps and babel preprocessor with gulp. Works. Only
issue is the jsdom.
